"""create events and ticket categories tables

Revision ID: bb5c19dcf40b
Revises: 98144c220a89
Create Date: 2026-08-28 14:25:23.506638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5c19dcf40b'
down_revision: Union[str, None] = '98144c220a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('seating_mode', sa.String(length=20), nullable=False),
    sa.Column('venue_name', sa.String(length=255), nullable=False),
    sa.Column('venue_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doors_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age_restriction', sa.String(length=20), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('online_link', sa.String(length=500), nullable=True),
    sa.Column('poster_image_url', sa.String(length=500), nullable=True),
    sa.Column('cancellation_policy', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='check_ends_after_starts'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_events_partner_id'), 'events', ['partner_id'], unique=False)
    op.create_table('event_ticket_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('max_per_booking', sa.Integer(), nullable=False),
    sa.Column('sales_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='check_capacity_positive'),
    sa.CheckConstraint('price_paise > 0', name='check_price_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='uq_event_category_name')
    )
    op.create_index(op.f('ix_event_ticket_categories_event_id'), 'event_ticket_categories', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_ticket_categories_event_id'), table_name='event_ticket_categories')
    op.drop_table('event_ticket_categories')
    op.drop_index(op.f('ix_events_partner_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###