"""add booking_type, showtime_id, ref_code to bookings; nullify event/tier fields

Revision ID: fd0cdee50289
Revises: 0003
Create Date: 2026-09-11 11:53:53.785906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0cdee50289'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_type', sa.Text(), server_default='EVENT', nullable=False))
    op.add_column('bookings', sa.Column('showtime_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('ref_code', sa.String(length=20), nullable=True))
    op.add_column('bookings', sa.Column('unit_price_paise', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('total_paise', sa.Integer(), nullable=False))
    op.alter_column('bookings', 'event_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('bookings', 'tier_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('bookings', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'idempotency_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_bookings_idempotency_key'), 'bookings', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_bookings_ref_code'), 'bookings', ['ref_code'], unique=True)
    op.create_index(op.f('ix_bookings_showtime_id'), 'bookings', ['showtime_id'], unique=False)
    op.drop_column('bookings', 'total_cents')
    op.drop_column('bookings', 'unit_price_cents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('unit_price_cents', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('total_cents', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_bookings_showtime_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_ref_code'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_idempotency_key'), table_name='bookings')
    op.alter_column('bookings', 'idempotency_key',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bookings', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'tier_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bookings', 'event_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('bookings', 'total_paise')
    op.drop_column('bookings', 'unit_price_paise')
    op.drop_column('bookings', 'ref_code')
    op.drop_column('bookings', 'showtime_id')
    op.drop_column('bookings', 'booking_type')
    # ### end Alembic commands ###